### ISSUE TITLE
Meilisearch log message potentially incorrect

### ISSUE THREAD

**Issue by sanders41** [Misery7100/ormwtf#1]
Just a quick FYI. The log message `logger.info(f"Index {cls.meili_config.index} updated")` [here](https://github.com/Misery7100/ormwtf/blob/ffdcfe22ab81811536a574f489a322a5a0bccb8a/ormwtf/extension/meilisearch/wrapper.py#L88C25-L88C79) is _sort of_ true.

Anything that returns `Task` or `TaskInfo`, such as `update_settings`, is asynchronous in Meilisearch. That means that the settings were sent to Meilisearch here, but it's possible the task fails, or hasn't completed yet. So the log message will most likely eventually become true, but if the task fails the log message will be wrong.

Either updating the message to say the settings have been sent or waiting for the task to complete and checking it are options here. Just know that with the waiting option there is the potential it takes a while depending on what the server is doing.

**Comment by Misery7100** [comment]
> Just a quick FYI. The log message `logger.info(f"Index {cls.meili_config.index} updated")` [here](https://github.com/Misery7100/ormwtf/blob/ffdcfe22ab81811536a574f489a322a5a0bccb8a/ormwtf/extension/meilisearch/wrapper.py#L88C25-L88C79) is _sort of_ true.
> 
> 
> 
> Anything that returns `Task` or `TaskInfo`, such as `update_settings`, is asynchronous in Meilisearch. That means that the settings were sent to Meilisearch here, but it's possible the task fails, or hasn't completed yet. So the log message will most likely eventually become true, but if the task fails the log message will be wrong.
> 
> 
> 
> Either updating the message to say the settings have been sent or waiting for the task to complete and checking it are options here. Just know that with the waiting option there is the potential it takes a while depending on what the server is doing.

Hello, @sanders41. Really surprised that you come here (not sure mb you just notified some way about deps). 

Regarding the note - yes, I'm aware of how it works in meilisearch, I had experience integrating official sdk where you have to wait until task completed to continue interaction properly. Basic idea now is just to make sure that corresponding task is submitted and index exists, as this is initialisation (e.g. I'm using this small repo within my backend projects) - it's costly to seek for successful task. I think it might be wrong (task interrupted or something is inconsistent) only in some hard load cases, isn't it?

**Comment by sanders41** [comment]
I saw this show up in the list of projects using my SDK and checked it out :smile: 

In the case of updating settings the server doesn't have to be under hard load for it to take a while. The reason is with settings updates it can trigger a  re-indexing of documents which in itself can take a while. Honestly I haven't testing this in a scenario where there is a long index time after updating settings, but I suppose the settings would report as updated and the indexing would be ongoing after that.

Really I won't recommend waiting here, just maybe updating the log message to make it clear the settings have been sent rather than saying they are updated. That way if it fails it's not as surprising. I would say 99.9% of the time your current message will be correct so if you prefer it as is no big deal, it's just a suggestion.

**Comment by Misery7100** [comment]
Aha, got it 👯 

Yes, that makes sense, will change that. Thank you
